openapi: 3.0.3
info:
  title: Dataverse Access Mail API
  description: Open source research data repository software.
  version: v6.8.1-SP
tags:
- name: Mail
paths:
  /mail/notifications:
    get:
      operationId: Mail_sendMail
      responses:
        '200':
          description: OK
      tags:
      - Mail
